# Generated by Django 4.2 on 2024-10-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['title'], 'verbose_name': 'Οργανισμός', 'verbose_name_plural': 'Οργανισμός'},
        ),
    ]
