# Generated by Django 4.2 on 2024-09-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_subscription'),
        ('users', '0004_userfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFile',
            new_name='Document',
        ),
    ]
