# Generated by Django 4.2 on 2024-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
