# Generated by Django 4.2 on 2024-10-03 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_enrollment'),
        ('users', '0007_alter_vacation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=users.models.student_directory_path, validators=[users.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.user_directory_path, validators=[users.validators.validate_file_extension])),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
