# Generated by Django 4.2 on 2024-10-06 14:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_document_file_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=users.models.user_directory_path),
        ),
    ]
