# Generated by Django 4.2 on 2024-10-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Αρχεία χρηστών', 'verbose_name_plural': 'Αρχεία χρηστών'},
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'verbose_name': 'Αρχεία προσωπικού', 'verbose_name_plural': 'Αρχεία προσωπικού'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Χρήστες', 'verbose_name_plural': 'Χρήστες'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'Άδειες προσωπικού', 'verbose_name_plural': 'Άδειες προσωπικού'},
        ),
    ]
