# Generated by Django 4.2 on 2024-10-16 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0011_alter_course_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Μαθήματα', 'verbose_name_plural': 'Μαθήματα'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user'], 'verbose_name': 'Μαθητές', 'verbose_name_plural': 'Μαθητές'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['start_date'], 'verbose_name': 'Εγγραφές', 'verbose_name_plural': 'Εγγραφές'},
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
