# Generated by Django 4.2 on 2024-10-15 16:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Έκδοση Εφαρμογής',
                'verbose_name_plural': 'Έκδοση Εφαρμογής',
            },
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('update_info', models.CharField(blank=True, max_length=250, null=True)),
                ('update_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.updateversion')),
            ],
            options={
                'verbose_name': 'Αναβαθμίσεις',
                'verbose_name_plural': 'Αναβαθμίσεις',
            },
        ),
    ]
